name: esfresso
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hexcolor: 2.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/deliveryman.png
    - assets/images/pizza.png
    - assets/images/google.png
    - assets/images/map.png
    - assets/images/profilepic.png
    - assets/images/filtericon.png
    - assets/images/fooditem.png
    - assets/images/bike.png
    - assets/images/timer.png
    - assets/itemList/item1.png
    - assets/itemList/item2.png
    - assets/itemList/item3.png
    - assets/itemList/item4.png
    - assets/itemList/item5.png
    - assets/popularList/popular1.png
    - assets/popularList/popular2.png
    - assets/popularList/Pizza 3.png
    - assets/popularList/Pizza 4.png

    

  uses-material-design: true

